title: "Paul Wiltsey - DevSecOps Engineer"
description: "Professional portfolio and resume site"
url: "https://pcwiltsey.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/

include:
  - _pages
